site_name: Open Source Guide
site_url: https://opensourceguide.nautilus-cyberneering.de/
nav:
    - Home: index.md
    - Best Practices: best-practices.md
    - Releases Process: releases-process.md
    - Choose a License: choose-a-license.md
    - Communication: communication.md
    - Contents Creation: contents-creation-guide.md
    - Governance Model: define-a-governance-model.md
    - Business Model: business-model-research.md